-------------------- TB_PICK_RESTRO_SESSION -----------------------------

CREATE TABLE `TB_PICK_RESTRO_SESSION` (
  `ID_TB_PICK_RESTRO_SESSION` int NOT NULL AUTO_INCREMENT,
  `ID_TB_SESSION` int NOT NULL,
  `ID_TB_USER` int NOT NULL,
  `ID_TB_RESTAURANT` int NOT NULL,
  `USER_STATUS` varchar(10) NOT NULL,
  `IS_REST_SELECTED` varchar(5) NOT NULL,
  `CREATED_BY` varchar(20) NOT NULL,
  `CREATED_DATETIME` datetime NOT NULL,
  `UPDATED_BY` varchar(20) DEFAULT NULL,
  `UPDATED_DATETIME` datetime DEFAULT NULL,
  PRIMARY KEY (`ID_TB_PICK_RESTRO_SESSION`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

-------------------- TB_RESTAURANT --------------------------------------
CREATE TABLE `TB_RESTAURANT` (
  `ID_TB_RESTAURANT` int NOT NULL AUTO_INCREMENT,
  `NAME` varchar(1000) NOT NULL,
  `ADDRESS` varchar(1000) NOT NULL,
  `CREATED_DATETIME` datetime NOT NULL,
  `CREATED_BY` varchar(20) NOT NULL,
  `UPDATED_BY` varchar(20) DEFAULT NULL,
  `UPDATED_DATETIME` datetime DEFAULT NULL,
  PRIMARY KEY (`ID_TB_RESTAURANT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

-------------------- TB_SESSION --------------------------------------
CREATE TABLE `TB_SESSION` (
  `ID_TB_SESSION` int NOT NULL AUTO_INCREMENT,
  `SESSION_TYPE` varchar(50) NOT NULL,
  `SESSION_DESC` varchar(1000) DEFAULT NULL,
  `CREATED_DATETIME` datetime NOT NULL,
  `CREATED_BY` varchar(20) NOT NULL,
  `END_DATETIME` datetime DEFAULT NULL,
  `UPDATED_DATETIME` datetime DEFAULT NULL,
  `UPDATED_BY` datetime DEFAULT NULL,
  PRIMARY KEY (`ID_TB_SESSION`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

-------------------- TB_USER --------------------------------------
CREATE TABLE `TB_USER` (
  `ID_TB_USER` int NOT NULL AUTO_INCREMENT,
  `USERNAME` varchar(20) NOT NULL,
  `PASSWORD` varchar(20) NOT NULL,
  `NAME` varchar(100) NOT NULL,
  `CREATED_BY` varchar(20) NOT NULL,
  `CREATED_DATETIME` datetime NOT NULL,
  `UPDATED_BY` varchar(20) DEFAULT NULL,
  `UPDATED_DATETIME` datetime DEFAULT NULL,
  PRIMARY KEY (`ID_TB_USER`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci