INSERT INTO `pickarestro`.`TB_RESTAURANT` (`ID_TB_RESTAURANT`, `NAME`, `ADDRESS`, `CREATED_DATETIME`, `CREATED_BY`) VALUES ('1', 'Masala Bar', '10 Siglap Road. Singapore - 450450', '2024-02-27 00:00:00', 'SYSTEM');
INSERT INTO `pickarestro`.`TB_RESTAURANT` (`ID_TB_RESTAURANT`, `NAME`, `ADDRESS`, `CREATED_DATETIME`, `CREATED_BY`) VALUES ('2', 'Wok connection', '10 Buffalo Road. Singapore - 101010', '2024-02-27 00:00:00', 'SYSTEM');
INSERT INTO `pickarestro`.`TB_RESTAURANT` (`ID_TB_RESTAURANT`, `NAME`, `ADDRESS`, `CREATED_DATETIME`, `CREATED_BY`) VALUES ('3', 'Wine connection', 'I12 Katong. Singapore - 110011', '2024-02-27 00:00:00', 'SYSTEM');
INSERT INTO `pickarestro`.`TB_RESTAURANT` (`ID_TB_RESTAURANT`, `NAME`, `ADDRESS`, `CREATED_DATETIME`, `CREATED_BY`) VALUES ('4', 'Bakery charm', 'Little India', '2024-02-27 00:00:00', 'SYSTEM');
INSERT INTO `pickarestro`.`TB_RESTAURANT` (`ID_TB_RESTAURANT`, `NAME`, `ADDRESS`, `CREATED_DATETIME`, `CREATED_BY`) VALUES ('5', 'Arbit petty', 'Orchard Road', '2024-02-27 00:00:00', 'SYSTEM');
INSERT INTO `pickarestro`.`TB_RESTAURANT` (`NAME`, `ADDRESS`, `CREATED_DATETIME`, `CREATED_BY`) VALUES ('Murugan Idli Shop', 'Syde Alwi Road', '2024-02-27 00:00:00', 'SYSTEM');

